// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqrIYzQHRQHKlGK0C2g3DeeDC3_ZC2yhg',
    appId: '1:86671789242:web:f287c2a63a57b9fc658683',
    messagingSenderId: '86671789242',
    projectId: 'exhibition-booth-managem-73fe8',
    authDomain: 'exhibition-booth-managem-73fe8.firebaseapp.com',
    storageBucket: 'exhibition-booth-managem-73fe8.firebasestorage.app',
    measurementId: 'G-DTRJTYY771',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBB1099gg-TVqtV0nStEHEdEJWOBUpd8U',
    appId: '1:86671789242:android:8059109e3656362c658683',
    messagingSenderId: '86671789242',
    projectId: 'exhibition-booth-managem-73fe8',
    storageBucket: 'exhibition-booth-managem-73fe8.firebasestorage.app',
  );
}
